#!/usr/bin/env ruby

require 'notify'

ROOT = File.dirname(File.realpath(__FILE__))
require "#{ROOT}/lib/bookshelf"

LocalBook.flagged.each do |lb|
  lb.unflag!
  lb.copy_to_remote
end

RemoteBook.all.each do |rb|
  rb.sync!
end